version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: bull
    versions:
    - 3.20.1
    - 3.21.0
    - 3.21.1
    - 3.22.0
    - 3.22.1
    - 3.22.3
  - dependency-name: ioredis
    versions:
    - 4.22.0
    - 4.23.0
    - 4.24.2
    - 4.24.3
    - 4.24.4
    - 4.24.5
    - 4.24.6
    - 4.25.0
    - 4.26.0
  - dependency-name: fastify
    versions:
    - 3.12.0
    - 3.13.0
    - 3.14.0
    - 3.14.1
    - 3.14.2
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
